language: php

php:
  - 7.0

before_script:
  - composer install

script:
  - pear install pear/PHP_CodeSniffer 
  - phpenv rehash
  - phpcs --standard=PSR2 src
  - phpunit --coverage-text --bootstrap tests/bootstrap.php tests/

notifications:
  email:
    - keith@shadycharacters.co.uk

