<?php
namespace Geissler\Converter\Standard\Basic;

class StandardMock extends StandardAbstract
{
    public function getCreator()
    {
        return parent::getCreator();
    }

    public function getParser()
    {
        return parent::getParser();
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 22:28:53.
 */
class StandardAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StandardMock
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StandardMock;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\Converter\Standard\Basic\StandardAbstract::parse
     */
    public function testParse()
    {
        $this->setExpectedException('ErrorException');
        $this->object->parse('');
    }

    /**
     * @covers Geissler\Converter\Standard\Basic\StandardAbstract::retrieve
     */
    public function testRetrieve()
    {
        $this->setExpectedException('ErrorException');
        $this->object->retrieve();
    }

    /**
     * @covers Geissler\Converter\Standard\Basic\StandardAbstract::getCreator
     */
    public function testGetCreator()
    {
        $this->setExpectedException('ErrorException');
        $this->object->getCreator();
    }

    /**
     * @covers Geissler\Converter\Standard\Basic\StandardAbstract::getParser
     */
    public function testGetParser()
    {
        $this->setExpectedException('ErrorException');
        $this->object->getParser();
    }
}
