<?php
namespace Geissler\Converter\Standard\RIS;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-10 at 18:01:23.
 */
class CreatorTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Creator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Creator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Geissler\Converter\Standard\RIS\Creator::create
     * @covers Geissler\Converter\Standard\RIS\Creator::getPerson
     * @covers Geissler\Converter\Standard\RIS\Creator::getDate
     * @covers Geissler\Converter\Standard\RIS\Creator::getType
     * @covers Geissler\Converter\Standard\RIS\Creator::retrieve
     * @dataProvider dataProviderCreate
     */
    public function testCreate($input, $output)
    {
        $parser =   new Parser();
        $this->assertTrue($parser->parse($input));
        $this->assertTrue($this->object->create($parser->retrieve()));
        $this->assertEquals($output, $this->object->retrieve());
    }

    public function dataProviderCreate()
    {
        return array(
            array(
                'TY  - CHAP
AU  - Franks,L.M.
TI  - Preface by an AIDS Victim
PY  - 1991
VL  - 3
T2  - Cancer, HIV and AIDS
T3  - Cancer Studies Series
A2  - Jackson, H.
A2  - Weisl, R.
SP  - vii- viii
CY  - Berkeley, CA
PB  - Berkeley Press
KW  - HIV
KW  - AIDS
DO  - DOI: 10.xxxxxxxxx
SN  - 0-679-40110-5
ER  - ',
                'TY  - CHAP
A2  - Jackson, H.
A2  - Weisl, R.
AU  - Franks, L.M.
PY  - 1991
SP  - vii- viii
SN  - 0-679-40110-5
PB  - Berkeley Press
CY  - Berkeley, CA
T1  - Preface by an AIDS Victim
T2  - Cancer, HIV and AIDS
VL  - 3
DO  - DOI: 10.xxxxxxxxx
KW  - HIV
KW  - AIDS
ER  - '
            )
        );
    }

    /**
     * @covers Geissler\Converter\Standard\RIS\Creator::create
     * @covers Geissler\Converter\Standard\RIS\Creator::retrieve
     */
    public function testRetrieve()
    {
        $this->assertFalse($this->object->create(new \Geissler\Converter\Model\Entries()));
        $this->assertFalse($this->object->retrieve());
    }
}
